// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string().name("world_id"),
  canvasId: __t.string().name("canvas_id"),
  name: __t.string(),
  kind: __t.string(),
  strengthMod: __t.i32().name("strength_mod"),
  hasLoadBearing: __t.bool().name("has_load_bearing"),
  movementGroupId: __t.string().name("movement_group_id"),
  active: __t.bool(),
  ownerActorId: __t.option(__t.string()).name("owner_actor_id"),
  capacityStone: __t.option(__t.u32()).name("capacity_stone"),
  baseExplorationFeet: __t.option(__t.u32()).name("base_exploration_feet"),
  baseCombatFeet: __t.option(__t.u32()).name("base_combat_feet"),
  baseRunningFeet: __t.option(__t.u32()).name("base_running_feet"),
  baseMilesPerDay: __t.option(__t.u32()).name("base_miles_per_day"),
  leftWieldingEntryId: __t.option(__t.string()).name("left_wielding_entry_id"),
  rightWieldingEntryId: __t.option(__t.string()).name("right_wielding_entry_id"),
});
