// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  objectId: __t.string().primaryKey().name("object_id"),
  worldId: __t.string().name("world_id"),
  canvasId: __t.string().name("canvas_id"),
  objectType: __t.string().name("object_type"),
  x: __t.f64(),
  y: __t.f64(),
  width: __t.f64(),
  height: __t.f64(),
  zIndex: __t.i32().name("z_index"),
  locked: __t.bool(),
  dataJson: __t.string().name("data_json"),
});
