// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.5 (commit d60138999206c06c776829072f46b5d1c1101f7e).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ClearAllTablesReducer from "./clear_all_tables_reducer";
import DeleteActorReducer from "./delete_actor_reducer";
import DeleteCarryGroupReducer from "./delete_carry_group_reducer";
import DeleteCustomGroupReducer from "./delete_custom_group_reducer";
import DeleteFreeSegmentPositionReducer from "./delete_free_segment_position_reducer";
import DeleteGroupFreeSegmentPositionReducer from "./delete_group_free_segment_position_reducer";
import DeleteGroupFreeSegmentPositionsByGroupReducer from "./delete_group_free_segment_positions_by_group_reducer";
import DeleteGroupListViewReducer from "./delete_group_list_view_reducer";
import DeleteGroupNodeOrderReducer from "./delete_group_node_order_reducer";
import DeleteGroupNodePositionReducer from "./delete_group_node_position_reducer";
import DeleteGroupNodePositionsByGroupReducer from "./delete_group_node_positions_by_group_reducer";
import DeleteGroupPositionReducer from "./delete_group_position_reducer";
import DeleteGroupSizeOverrideReducer from "./delete_group_size_override_reducer";
import DeleteGroupTitleOverrideReducer from "./delete_group_title_override_reducer";
import DeleteInventoryEntryReducer from "./delete_inventory_entry_reducer";
import DeleteItemDefinitionReducer from "./delete_item_definition_reducer";
import DeleteLabelReducer from "./delete_label_reducer";
import DeleteLayoutExpandedReducer from "./delete_layout_expanded_reducer";
import DeleteMovementGroupReducer from "./delete_movement_group_reducer";
import DeleteNodeContainmentReducer from "./delete_node_containment_reducer";
import DeleteNodeGroupOverrideReducer from "./delete_node_group_override_reducer";
import DeleteNodePositionReducer from "./delete_node_position_reducer";
import DeleteNodeSizeOverrideReducer from "./delete_node_size_override_reducer";
import DeleteNodeTitleOverrideReducer from "./delete_node_title_override_reducer";
import DeleteSettingReducer from "./delete_setting_reducer";
import EnsureCanvasReducer from "./ensure_canvas_reducer";
import EnsureWorldReducer from "./ensure_world_reducer";
import RenameCanvasReducer from "./rename_canvas_reducer";
import RenameWorldReducer from "./rename_world_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetLayoutStateReducer from "./set_layout_state_reducer";
import SetPresenceReducer from "./set_presence_reducer";
import SetUserRoleReducer from "./set_user_role_reducer";
import SetWorldStateReducer from "./set_world_state_reducer";
import UpdateCameraReducer from "./update_camera_reducer";
import UpdateCursorReducer from "./update_cursor_reducer";
import UpsertActorReducer from "./upsert_actor_reducer";
import UpsertCarryGroupReducer from "./upsert_carry_group_reducer";
import UpsertCustomGroupReducer from "./upsert_custom_group_reducer";
import UpsertFreeSegmentPositionReducer from "./upsert_free_segment_position_reducer";
import UpsertGroupFreeSegmentPositionReducer from "./upsert_group_free_segment_position_reducer";
import UpsertGroupListViewReducer from "./upsert_group_list_view_reducer";
import UpsertGroupNodeOrderReducer from "./upsert_group_node_order_reducer";
import UpsertGroupNodePositionReducer from "./upsert_group_node_position_reducer";
import UpsertGroupPositionReducer from "./upsert_group_position_reducer";
import UpsertGroupSizeOverrideReducer from "./upsert_group_size_override_reducer";
import UpsertGroupTitleOverrideReducer from "./upsert_group_title_override_reducer";
import UpsertInventoryEntryReducer from "./upsert_inventory_entry_reducer";
import UpsertItemDefinitionReducer from "./upsert_item_definition_reducer";
import UpsertLabelReducer from "./upsert_label_reducer";
import UpsertLayoutExpandedReducer from "./upsert_layout_expanded_reducer";
import UpsertMovementGroupReducer from "./upsert_movement_group_reducer";
import UpsertNodeContainmentReducer from "./upsert_node_containment_reducer";
import UpsertNodeGroupOverrideReducer from "./upsert_node_group_override_reducer";
import UpsertNodePositionReducer from "./upsert_node_position_reducer";
import UpsertNodeSizeOverrideReducer from "./upsert_node_size_override_reducer";
import UpsertNodeTitleOverrideReducer from "./upsert_node_title_override_reducer";
import UpsertSettingReducer from "./upsert_setting_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActorsRow from "./actors_table";
import CanvasSlugHistoryRow from "./canvas_slug_history_table";
import CanvasesRow from "./canvases_table";
import CarryGroupsRow from "./carry_groups_table";
import CustomGroupsRow from "./custom_groups_table";
import FreeSegmentPositionsRow from "./free_segment_positions_table";
import GroupFreeSegmentPositionsRow from "./group_free_segment_positions_table";
import GroupListViewRow from "./group_list_view_table";
import GroupNodeOrdersRow from "./group_node_orders_table";
import GroupNodePositionsRow from "./group_node_positions_table";
import GroupPositionsRow from "./group_positions_table";
import GroupSizeOverridesRow from "./group_size_overrides_table";
import GroupTitleOverridesRow from "./group_title_overrides_table";
import InventoryEntriesRow from "./inventory_entries_table";
import ItemDefinitionsRow from "./item_definitions_table";
import LabelsRow from "./labels_table";
import LayoutExpandedRow from "./layout_expanded_table";
import MovementGroupsRow from "./movement_groups_table";
import NodeContainmentRow from "./node_containment_table";
import NodeGroupOverridesRow from "./node_group_overrides_table";
import NodePositionsRow from "./node_positions_table";
import NodeSizeOverridesRow from "./node_size_overrides_table";
import NodeTitleOverridesRow from "./node_title_overrides_table";
import SettingsRow from "./settings_table";
import UserCamerasRow from "./user_cameras_table";
import UserCursorsRow from "./user_cursors_table";
import UserPresencesRow from "./user_presences_table";
import UsersRow from "./users_table";
import WorldSlugHistoryRow from "./world_slug_history_table";
import WorldsRow from "./worlds_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  actors: __table({
    name: 'actors',
    indexes: [
      { accessor: 'id', name: 'actors_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorldCanvas', name: 'actors_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
      { accessor: 'worldId', name: 'actors_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'actors_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActorsRow),
  canvas_slug_history: __table({
    name: 'canvas_slug_history',
    indexes: [
      { accessor: 'id', name: 'canvas_slug_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorldSlug', name: 'canvas_slug_history_world_id_slug_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'slug',
      ] },
    ],
    constraints: [
      { name: 'canvas_slug_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CanvasSlugHistoryRow),
  canvases: __table({
    name: 'canvases',
    indexes: [
      { accessor: 'id', name: 'canvases_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorldSlug', name: 'canvases_world_id_slug_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'slug',
      ] },
    ],
    constraints: [
      { name: 'canvases_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CanvasesRow),
  carry_groups: __table({
    name: 'carry_groups',
    indexes: [
      { accessor: 'id', name: 'carry_groups_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ownerActorId', name: 'carry_groups_owner_actor_id_idx_btree', algorithm: 'btree', columns: [
        'ownerActorId',
      ] },
      { accessor: 'byWorldCanvas', name: 'carry_groups_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
      { accessor: 'worldId', name: 'carry_groups_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'carry_groups_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CarryGroupsRow),
  custom_groups: __table({
    name: 'custom_groups',
    indexes: [
      { accessor: 'groupId', name: 'custom_groups_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'custom_groups_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'custom_groups_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, CustomGroupsRow),
  free_segment_positions: __table({
    name: 'free_segment_positions',
    indexes: [
      { accessor: 'segmentId', name: 'free_segment_positions_segment_id_idx_btree', algorithm: 'btree', columns: [
        'segmentId',
      ] },
      { accessor: 'byWorldCanvas', name: 'free_segment_positions_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'free_segment_positions_segment_id_key', constraint: 'unique', columns: ['segmentId'] },
    ],
  }, FreeSegmentPositionsRow),
  group_free_segment_positions: __table({
    name: 'group_free_segment_positions',
    indexes: [
      { accessor: 'groupId', name: 'group_free_segment_positions_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'id', name: 'group_free_segment_positions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'segmentId', name: 'group_free_segment_positions_segment_id_idx_btree', algorithm: 'btree', columns: [
        'segmentId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_free_segment_positions_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_free_segment_positions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupFreeSegmentPositionsRow),
  group_list_view: __table({
    name: 'group_list_view',
    indexes: [
      { accessor: 'groupId', name: 'group_list_view_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_list_view_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_list_view_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupListViewRow),
  group_node_orders: __table({
    name: 'group_node_orders',
    indexes: [
      { accessor: 'groupId', name: 'group_node_orders_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_node_orders_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_node_orders_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupNodeOrdersRow),
  group_node_positions: __table({
    name: 'group_node_positions',
    indexes: [
      { accessor: 'groupId', name: 'group_node_positions_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'id', name: 'group_node_positions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'nodeId', name: 'group_node_positions_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_node_positions_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_node_positions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupNodePositionsRow),
  group_positions: __table({
    name: 'group_positions',
    indexes: [
      { accessor: 'groupId', name: 'group_positions_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_positions_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_positions_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupPositionsRow),
  group_size_overrides: __table({
    name: 'group_size_overrides',
    indexes: [
      { accessor: 'groupId', name: 'group_size_overrides_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_size_overrides_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_size_overrides_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupSizeOverridesRow),
  group_title_overrides: __table({
    name: 'group_title_overrides',
    indexes: [
      { accessor: 'groupId', name: 'group_title_overrides_group_id_idx_btree', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { accessor: 'byWorldCanvas', name: 'group_title_overrides_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'group_title_overrides_group_id_key', constraint: 'unique', columns: ['groupId'] },
    ],
  }, GroupTitleOverridesRow),
  inventory_entries: __table({
    name: 'inventory_entries',
    indexes: [
      { accessor: 'actorId', name: 'inventory_entries_actor_id_idx_btree', algorithm: 'btree', columns: [
        'actorId',
      ] },
      { accessor: 'id', name: 'inventory_entries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorldCanvas', name: 'inventory_entries_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
      { accessor: 'worldId', name: 'inventory_entries_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'inventory_entries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InventoryEntriesRow),
  item_definitions: __table({
    name: 'item_definitions',
    indexes: [
      { accessor: 'id', name: 'item_definitions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'worldId', name: 'item_definitions_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'item_definitions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemDefinitionsRow),
  labels: __table({
    name: 'labels',
    indexes: [
      { accessor: 'labelId', name: 'labels_label_id_idx_btree', algorithm: 'btree', columns: [
        'labelId',
      ] },
      { accessor: 'byWorldCanvas', name: 'labels_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'labels_label_id_key', constraint: 'unique', columns: ['labelId'] },
    ],
  }, LabelsRow),
  layout_expanded: __table({
    name: 'layout_expanded',
    indexes: [
      { accessor: 'containerId', name: 'layout_expanded_container_id_idx_btree', algorithm: 'btree', columns: [
        'containerId',
      ] },
      { accessor: 'byWorldCanvas', name: 'layout_expanded_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'layout_expanded_container_id_key', constraint: 'unique', columns: ['containerId'] },
    ],
  }, LayoutExpandedRow),
  movement_groups: __table({
    name: 'movement_groups',
    indexes: [
      { accessor: 'id', name: 'movement_groups_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorldCanvas', name: 'movement_groups_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
      { accessor: 'worldId', name: 'movement_groups_world_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
      ] },
    ],
    constraints: [
      { name: 'movement_groups_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MovementGroupsRow),
  node_containment: __table({
    name: 'node_containment',
    indexes: [
      { accessor: 'containerNodeId', name: 'node_containment_container_node_id_idx_btree', algorithm: 'btree', columns: [
        'containerNodeId',
      ] },
      { accessor: 'nodeId', name: 'node_containment_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'node_containment_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'node_containment_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeContainmentRow),
  node_group_overrides: __table({
    name: 'node_group_overrides',
    indexes: [
      { accessor: 'nodeId', name: 'node_group_overrides_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'node_group_overrides_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'node_group_overrides_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeGroupOverridesRow),
  node_positions: __table({
    name: 'node_positions',
    indexes: [
      { accessor: 'nodeId', name: 'node_positions_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'node_positions_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'node_positions_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodePositionsRow),
  node_size_overrides: __table({
    name: 'node_size_overrides',
    indexes: [
      { accessor: 'nodeId', name: 'node_size_overrides_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'node_size_overrides_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'node_size_overrides_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeSizeOverridesRow),
  node_title_overrides: __table({
    name: 'node_title_overrides',
    indexes: [
      { accessor: 'nodeId', name: 'node_title_overrides_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'byWorldCanvas', name: 'node_title_overrides_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'node_title_overrides_node_id_key', constraint: 'unique', columns: ['nodeId'] },
    ],
  }, NodeTitleOverridesRow),
  settings: __table({
    name: 'settings',
    indexes: [
      { accessor: 'key', name: 'settings_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'byWorldCanvas', name: 'settings_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SettingsRow),
  user_cameras: __table({
    name: 'user_cameras',
    indexes: [
      { accessor: 'id', name: 'user_cameras_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identityHex', name: 'user_cameras_identity_hex_idx_btree', algorithm: 'btree', columns: [
        'identityHex',
      ] },
      { accessor: 'byWorldCanvas', name: 'user_cameras_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'user_cameras_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserCamerasRow),
  user_cursors: __table({
    name: 'user_cursors',
    indexes: [
      { accessor: 'id', name: 'user_cursors_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identityHex', name: 'user_cursors_identity_hex_idx_btree', algorithm: 'btree', columns: [
        'identityHex',
      ] },
      { accessor: 'byWorldCanvas', name: 'user_cursors_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'user_cursors_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserCursorsRow),
  user_presences: __table({
    name: 'user_presences',
    indexes: [
      { accessor: 'id', name: 'user_presences_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identityHex', name: 'user_presences_identity_hex_idx_btree', algorithm: 'btree', columns: [
        'identityHex',
      ] },
      { accessor: 'byWorldCanvas', name: 'user_presences_world_id_canvas_id_idx_btree', algorithm: 'btree', columns: [
        'worldId',
        'canvasId',
      ] },
    ],
    constraints: [
      { name: 'user_presences_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserPresencesRow),
  users: __table({
    name: 'users',
    indexes: [
      { accessor: 'identityHex', name: 'users_identity_hex_idx_btree', algorithm: 'btree', columns: [
        'identityHex',
      ] },
    ],
    constraints: [
      { name: 'users_identity_hex_key', constraint: 'unique', columns: ['identityHex'] },
    ],
  }, UsersRow),
  world_slug_history: __table({
    name: 'world_slug_history',
    indexes: [
      { accessor: 'id', name: 'world_slug_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slug', name: 'world_slug_history_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'world_slug_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSlugHistoryRow),
  worlds: __table({
    name: 'worlds',
    indexes: [
      { accessor: 'id', name: 'worlds_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slug', name: 'worlds_slug_idx_btree', algorithm: 'btree', columns: [
        'slug',
      ] },
    ],
    constraints: [
      { name: 'worlds_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("clear_all_tables", ClearAllTablesReducer),
  __reducerSchema("delete_actor", DeleteActorReducer),
  __reducerSchema("delete_carry_group", DeleteCarryGroupReducer),
  __reducerSchema("delete_custom_group", DeleteCustomGroupReducer),
  __reducerSchema("delete_free_segment_position", DeleteFreeSegmentPositionReducer),
  __reducerSchema("delete_group_free_segment_position", DeleteGroupFreeSegmentPositionReducer),
  __reducerSchema("delete_group_free_segment_positions_by_group", DeleteGroupFreeSegmentPositionsByGroupReducer),
  __reducerSchema("delete_group_list_view", DeleteGroupListViewReducer),
  __reducerSchema("delete_group_node_order", DeleteGroupNodeOrderReducer),
  __reducerSchema("delete_group_node_position", DeleteGroupNodePositionReducer),
  __reducerSchema("delete_group_node_positions_by_group", DeleteGroupNodePositionsByGroupReducer),
  __reducerSchema("delete_group_position", DeleteGroupPositionReducer),
  __reducerSchema("delete_group_size_override", DeleteGroupSizeOverrideReducer),
  __reducerSchema("delete_group_title_override", DeleteGroupTitleOverrideReducer),
  __reducerSchema("delete_inventory_entry", DeleteInventoryEntryReducer),
  __reducerSchema("delete_item_definition", DeleteItemDefinitionReducer),
  __reducerSchema("delete_label", DeleteLabelReducer),
  __reducerSchema("delete_layout_expanded", DeleteLayoutExpandedReducer),
  __reducerSchema("delete_movement_group", DeleteMovementGroupReducer),
  __reducerSchema("delete_node_containment", DeleteNodeContainmentReducer),
  __reducerSchema("delete_node_group_override", DeleteNodeGroupOverrideReducer),
  __reducerSchema("delete_node_position", DeleteNodePositionReducer),
  __reducerSchema("delete_node_size_override", DeleteNodeSizeOverrideReducer),
  __reducerSchema("delete_node_title_override", DeleteNodeTitleOverrideReducer),
  __reducerSchema("delete_setting", DeleteSettingReducer),
  __reducerSchema("ensure_canvas", EnsureCanvasReducer),
  __reducerSchema("ensure_world", EnsureWorldReducer),
  __reducerSchema("rename_canvas", RenameCanvasReducer),
  __reducerSchema("rename_world", RenameWorldReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_layout_state", SetLayoutStateReducer),
  __reducerSchema("set_presence", SetPresenceReducer),
  __reducerSchema("set_user_role", SetUserRoleReducer),
  __reducerSchema("set_world_state", SetWorldStateReducer),
  __reducerSchema("update_camera", UpdateCameraReducer),
  __reducerSchema("update_cursor", UpdateCursorReducer),
  __reducerSchema("upsert_actor", UpsertActorReducer),
  __reducerSchema("upsert_carry_group", UpsertCarryGroupReducer),
  __reducerSchema("upsert_custom_group", UpsertCustomGroupReducer),
  __reducerSchema("upsert_free_segment_position", UpsertFreeSegmentPositionReducer),
  __reducerSchema("upsert_group_free_segment_position", UpsertGroupFreeSegmentPositionReducer),
  __reducerSchema("upsert_group_list_view", UpsertGroupListViewReducer),
  __reducerSchema("upsert_group_node_order", UpsertGroupNodeOrderReducer),
  __reducerSchema("upsert_group_node_position", UpsertGroupNodePositionReducer),
  __reducerSchema("upsert_group_position", UpsertGroupPositionReducer),
  __reducerSchema("upsert_group_size_override", UpsertGroupSizeOverrideReducer),
  __reducerSchema("upsert_group_title_override", UpsertGroupTitleOverrideReducer),
  __reducerSchema("upsert_inventory_entry", UpsertInventoryEntryReducer),
  __reducerSchema("upsert_item_definition", UpsertItemDefinitionReducer),
  __reducerSchema("upsert_label", UpsertLabelReducer),
  __reducerSchema("upsert_layout_expanded", UpsertLayoutExpandedReducer),
  __reducerSchema("upsert_movement_group", UpsertMovementGroupReducer),
  __reducerSchema("upsert_node_containment", UpsertNodeContainmentReducer),
  __reducerSchema("upsert_node_group_override", UpsertNodeGroupOverrideReducer),
  __reducerSchema("upsert_node_position", UpsertNodePositionReducer),
  __reducerSchema("upsert_node_size_override", UpsertNodeSizeOverrideReducer),
  __reducerSchema("upsert_node_title_override", UpsertNodeTitleOverrideReducer),
  __reducerSchema("upsert_setting", UpsertSettingReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.5" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

