// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  worldId: __t.string().name("world_id"),
  actorId: __t.string().name("actor_id"),
  itemDefId: __t.string().name("item_def_id"),
  quantity: __t.u32(),
  zone: __t.string(),
  stateWorn: __t.option(__t.bool()).name("state_worn"),
  stateAttached: __t.option(__t.bool()).name("state_attached"),
  stateHeldHands: __t.option(__t.u32()).name("state_held_hands"),
  stateDropped: __t.option(__t.bool()).name("state_dropped"),
  stateInaccessible: __t.option(__t.bool()).name("state_inaccessible"),
  carryGroupId: __t.option(__t.string()).name("carry_group_id"),
});
