// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  worldSlug: __t.string().name("world_slug"),
  canonicalName: __t.string().name("canonical_name"),
  kind: __t.string(),
  sixthsPerUnit: __t.option(__t.u32()).name("sixths_per_unit"),
  armorClass: __t.option(__t.u32()).name("armor_class"),
  priceInGp: __t.option(__t.f64()).name("price_in_gp"),
  isFungibleVisual: __t.option(__t.bool()).name("is_fungible_visual"),
});
