// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Actors = __t.object("Actors", {
  id: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  strengthMod: __t.i32(),
  hasLoadBearing: __t.bool(),
  movementGroupId: __t.string(),
  active: __t.bool(),
  ownerActorId: __t.option(__t.string()),
  capacityStone: __t.option(__t.u32()),
  baseExplorationFeet: __t.option(__t.u32()),
  baseCombatFeet: __t.option(__t.u32()),
  baseRunningFeet: __t.option(__t.u32()),
  baseMilesPerDay: __t.option(__t.u32()),
  leftWieldingEntryId: __t.option(__t.string()),
  rightWieldingEntryId: __t.option(__t.string()),
});
export type Actors = __Infer<typeof Actors>;

export const CarryGroups = __t.object("CarryGroups", {
  id: __t.string(),
  ownerActorId: __t.string(),
  name: __t.string(),
  dropped: __t.bool(),
});
export type CarryGroups = __Infer<typeof CarryGroups>;

export const CustomGroups = __t.object("CustomGroups", {
  groupId: __t.string(),
  title: __t.string(),
});
export type CustomGroups = __Infer<typeof CustomGroups>;

export const FreeSegmentPositions = __t.object("FreeSegmentPositions", {
  segmentId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type FreeSegmentPositions = __Infer<typeof FreeSegmentPositions>;

export const GroupFreeSegmentPositions = __t.object("GroupFreeSegmentPositions", {
  id: __t.string(),
  groupId: __t.string(),
  segmentId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type GroupFreeSegmentPositions = __Infer<typeof GroupFreeSegmentPositions>;

export const GroupListView = __t.object("GroupListView", {
  groupId: __t.string(),
  enabled: __t.bool(),
});
export type GroupListView = __Infer<typeof GroupListView>;

export const GroupNodeOrders = __t.object("GroupNodeOrders", {
  groupId: __t.string(),
  nodeIdsJson: __t.string(),
});
export type GroupNodeOrders = __Infer<typeof GroupNodeOrders>;

export const GroupNodePositions = __t.object("GroupNodePositions", {
  id: __t.string(),
  groupId: __t.string(),
  nodeId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type GroupNodePositions = __Infer<typeof GroupNodePositions>;

export const GroupPositions = __t.object("GroupPositions", {
  groupId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type GroupPositions = __Infer<typeof GroupPositions>;

export const GroupSizeOverrides = __t.object("GroupSizeOverrides", {
  groupId: __t.string(),
  width: __t.f64(),
  height: __t.f64(),
});
export type GroupSizeOverrides = __Infer<typeof GroupSizeOverrides>;

export const GroupTitleOverrides = __t.object("GroupTitleOverrides", {
  groupId: __t.string(),
  title: __t.string(),
});
export type GroupTitleOverrides = __Infer<typeof GroupTitleOverrides>;

export const InventoryEntries = __t.object("InventoryEntries", {
  id: __t.string(),
  actorId: __t.string(),
  itemDefId: __t.string(),
  quantity: __t.u32(),
  zone: __t.string(),
  stateWorn: __t.option(__t.bool()),
  stateAttached: __t.option(__t.bool()),
  stateHeldHands: __t.option(__t.u32()),
  stateDropped: __t.option(__t.bool()),
  stateInaccessible: __t.option(__t.bool()),
  carryGroupId: __t.option(__t.string()),
});
export type InventoryEntries = __Infer<typeof InventoryEntries>;

export const ItemDefinitions = __t.object("ItemDefinitions", {
  id: __t.string(),
  canonicalName: __t.string(),
  kind: __t.string(),
  sixthsPerUnit: __t.option(__t.u32()),
  armorClass: __t.option(__t.u32()),
  priceInGp: __t.option(__t.f64()),
  isFungibleVisual: __t.option(__t.bool()),
});
export type ItemDefinitions = __Infer<typeof ItemDefinitions>;

export const Labels = __t.object("Labels", {
  labelId: __t.string(),
  text: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type Labels = __Infer<typeof Labels>;

export const MovementGroups = __t.object("MovementGroups", {
  id: __t.string(),
  name: __t.string(),
  active: __t.bool(),
});
export type MovementGroups = __Infer<typeof MovementGroups>;

export const NodeContainment = __t.object("NodeContainment", {
  nodeId: __t.string(),
  containerNodeId: __t.string(),
});
export type NodeContainment = __Infer<typeof NodeContainment>;

export const NodeGroupOverrides = __t.object("NodeGroupOverrides", {
  nodeId: __t.string(),
  groupId: __t.option(__t.string()),
});
export type NodeGroupOverrides = __Infer<typeof NodeGroupOverrides>;

export const NodePositions = __t.object("NodePositions", {
  nodeId: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
});
export type NodePositions = __Infer<typeof NodePositions>;

export const NodeSizeOverrides = __t.object("NodeSizeOverrides", {
  nodeId: __t.string(),
  slotCols: __t.u32(),
  slotRows: __t.u32(),
});
export type NodeSizeOverrides = __Infer<typeof NodeSizeOverrides>;

export const NodeTitleOverrides = __t.object("NodeTitleOverrides", {
  nodeId: __t.string(),
  title: __t.string(),
});
export type NodeTitleOverrides = __Infer<typeof NodeTitleOverrides>;

export const Settings = __t.object("Settings", {
  key: __t.string(),
  valueNum: __t.option(__t.u32()),
});
export type Settings = __Infer<typeof Settings>;

export const UserCursors = __t.object("UserCursors", {
  identityHex: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  viewportScale: __t.option(__t.f64()),
});
export type UserCursors = __Infer<typeof UserCursors>;

export const Users = __t.object("Users", {
  identityHex: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  online: __t.bool(),
  lastSeenMs: __t.f64(),
});
export type Users = __Infer<typeof Users>;

