// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  objectId: __t.string(),
  objectType: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  width: __t.f64(),
  height: __t.f64(),
  zIndex: __t.i32(),
  locked: __t.bool(),
  dataJson: __t.string(),
};
