// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  actorId: __t.string(),
  itemDefId: __t.string(),
  quantity: __t.u32(),
  zone: __t.string(),
  stateWorn: __t.option(__t.bool()),
  stateAttached: __t.option(__t.bool()),
  stateHeldHands: __t.option(__t.u32()),
  stateDropped: __t.option(__t.bool()),
  stateInaccessible: __t.option(__t.bool()),
  carryGroupId: __t.option(__t.string()),
};
