// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  canonicalName: __t.string(),
  kind: __t.string(),
  sixthsPerUnit: __t.option(__t.u32()),
  armorClass: __t.option(__t.u32()),
  priceInGp: __t.option(__t.f64()),
  isFungibleVisual: __t.option(__t.bool()),
};
