// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  strengthMod: __t.i32(),
  hasLoadBearing: __t.bool(),
  movementGroupId: __t.string(),
  active: __t.bool(),
  ownerActorId: __t.option(__t.string()),
  capacityStone: __t.option(__t.u32()),
  baseExplorationFeet: __t.option(__t.u32()),
  baseCombatFeet: __t.option(__t.u32()),
  baseRunningFeet: __t.option(__t.u32()),
  baseMilesPerDay: __t.option(__t.u32()),
  leftWieldingEntryId: __t.option(__t.string()),
  rightWieldingEntryId: __t.option(__t.string()),
};
