// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identityHex: __t.string().name("identity_hex"),
  worldSlug: __t.string().name("world_slug"),
  canvasSlug: __t.string().name("canvas_slug"),
  x: __t.f64(),
  y: __t.f64(),
  viewportScale: __t.option(__t.f64()).name("viewport_scale"),
});
