import type { CanonicalState } from './domain/types'

export const sampleState: CanonicalState = {
  actors: {
    cutthroat: {
      id: 'cutthroat',
      name: 'Cutthroat',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    prophet: {
      id: 'prophet',
      name: 'Prophet',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    exorcist: {
      id: 'exorcist',
      name: 'Exorcist',
      kind: 'pc',
      stats: { strengthMod: 1, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    templar: {
      id: 'templar',
      name: 'Templar',
      kind: 'pc',
      stats: { strengthMod: 2, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
  },
  movementGroups: {
    party: { id: 'party', name: 'Expedition Group', active: true },
  },
  carryGroups: {},
  itemDefinitions: {
    handAxe: { id: 'handAxe', canonicalName: 'Hand axe', kind: 'bulky' },
    dagger: { id: 'dagger', canonicalName: 'Dagger', kind: 'standard', sixthsPerUnit: 1 },
    leatherArmor: { id: 'leatherArmor', canonicalName: 'Leather armor', kind: 'armor', armorClass: 2 },
    backpack: { id: 'backpack', canonicalName: 'Backpack', kind: 'standard', sixthsPerUnit: 1 },
    ironSpike: { id: 'ironSpike', canonicalName: 'Iron spike', kind: 'standard', sixthsPerUnit: 1 },
    smallHammer: { id: 'smallHammer', canonicalName: 'Small hammer', kind: 'standard', sixthsPerUnit: 1 },
    militaryOil: { id: 'militaryOil', canonicalName: 'Flask of military oil', kind: 'standard', sixthsPerUnit: 1 },
    tinderbox: { id: 'tinderbox', canonicalName: 'Tinderbox', kind: 'standard', sixthsPerUnit: 1 },
    torch: { id: 'torch', canonicalName: 'Torch', kind: 'standard', sixthsPerUnit: 1 },
    waterskin: { id: 'waterskin', canonicalName: 'Waterskin', kind: 'standard', sixthsPerUnit: 1 },
    ironRationsDay: {
      id: 'ironRationsDay',
      canonicalName: "1 day's iron rations",
      kind: 'standard',
      sixthsPerUnit: 1,
      priceInGp: 1 / 7,
    },
    holySymbolWingedSun: {
      id: 'holySymbolWingedSun',
      canonicalName: 'Holy symbol (winged sun of Ammonar)',
      kind: 'standard',
      sixthsPerUnit: 1,
    },
    sling: { id: 'sling', canonicalName: 'Sling', kind: 'standard', sixthsPerUnit: 1 },
    slingStones30: { id: 'slingStones30', canonicalName: '30 sling stones', kind: 'standard', sixthsPerUnit: 1 },
    staff: { id: 'staff', canonicalName: 'Staff', kind: 'bulky' },
    rope50: { id: 'rope50', canonicalName: "50' rope", kind: 'standard', sixthsPerUnit: 6 },
    warhammer: { id: 'warhammer', canonicalName: 'Warhammer', kind: 'bulky' },
    steelShield: { id: 'steelShield', canonicalName: 'Steel shield', kind: 'bulky' },
    bandedPlateArmor: { id: 'bandedPlateArmor', canonicalName: 'Banded plate armor', kind: 'armor', armorClass: 6 },
    holyWater: { id: 'holyWater', canonicalName: 'Flask of holy water', kind: 'standard', sixthsPerUnit: 1 },
    manacles: { id: 'manacles', canonicalName: 'Manacles', kind: 'standard', sixthsPerUnit: 1 },
    polishedSword: { id: 'polishedSword', canonicalName: 'Polished sword', kind: 'bulky' },
    ridingSaddleTack: { id: 'ridingSaddleTack', canonicalName: 'Riding saddle and tack', kind: 'standard', sixthsPerUnit: 4 },
    leatherSaddlebag: { id: 'leatherSaddlebag', canonicalName: 'Leather saddlebag', kind: 'standard', sixthsPerUnit: 3 },
  },
  inventoryEntries: {
    cutthroatHandAxe: {
      id: 'cutthroatHandAxe',
      actorId: 'cutthroat',
      itemDefId: 'handAxe',
      quantity: 1,
      zone: 'attached',
    },
    cutthroatDagger: {
      id: 'cutthroatDagger',
      actorId: 'cutthroat',
      itemDefId: 'dagger',
      quantity: 1,
      zone: 'attached',
      state: { heldHands: 1 },
    },
    cutthroatLeatherArmor: {
      id: 'cutthroatLeatherArmor',
      actorId: 'cutthroat',
      itemDefId: 'leatherArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    cutthroatBackpack: {
      id: 'cutthroatBackpack',
      actorId: 'cutthroat',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatIronSpike: {
      id: 'cutthroatIronSpike',
      actorId: 'cutthroat',
      itemDefId: 'ironSpike',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatSmallHammer: {
      id: 'cutthroatSmallHammer',
      actorId: 'cutthroat',
      itemDefId: 'smallHammer',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatMilitaryOil: {
      id: 'cutthroatMilitaryOil',
      actorId: 'cutthroat',
      itemDefId: 'militaryOil',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatTinderbox: {
      id: 'cutthroatTinderbox',
      actorId: 'cutthroat',
      itemDefId: 'tinderbox',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatTorchA: { id: 'cutthroatTorchA', actorId: 'cutthroat', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    cutthroatTorchB: { id: 'cutthroatTorchB', actorId: 'cutthroat', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    cutthroatTorchC: { id: 'cutthroatTorchC', actorId: 'cutthroat', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    cutthroatWaterskin: {
      id: 'cutthroatWaterskin',
      actorId: 'cutthroat',
      itemDefId: 'waterskin',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatRation1: { id: 'cutthroatRation1', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation2: { id: 'cutthroatRation2', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation3: { id: 'cutthroatRation3', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation4: { id: 'cutthroatRation4', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation5: { id: 'cutthroatRation5', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation6: { id: 'cutthroatRation6', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRation7: { id: 'cutthroatRation7', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetHolySymbol: {
      id: 'prophetHolySymbol',
      actorId: 'prophet',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    prophetSling: {
      id: 'prophetSling',
      actorId: 'prophet',
      itemDefId: 'sling',
      quantity: 1,
      zone: 'attached',
    },
    prophetSlingStones: {
      id: 'prophetSlingStones',
      actorId: 'prophet',
      itemDefId: 'slingStones30',
      quantity: 1,
      zone: 'accessible',
    },
    prophetStaff: {
      id: 'prophetStaff',
      actorId: 'prophet',
      itemDefId: 'staff',
      quantity: 1,
      zone: 'attached',
    },
    prophetLeatherArmor: {
      id: 'prophetLeatherArmor',
      actorId: 'prophet',
      itemDefId: 'leatherArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    prophetBackpack: {
      id: 'prophetBackpack',
      actorId: 'prophet',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    prophetRation1: { id: 'prophetRation1', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation2: { id: 'prophetRation2', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation3: { id: 'prophetRation3', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation4: { id: 'prophetRation4', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation5: { id: 'prophetRation5', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation6: { id: 'prophetRation6', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRation7: { id: 'prophetRation7', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    exorcistHolySymbol: {
      id: 'exorcistHolySymbol',
      actorId: 'exorcist',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
    },
    exorcistWarhammer: {
      id: 'exorcistWarhammer',
      actorId: 'exorcist',
      itemDefId: 'warhammer',
      quantity: 1,
      zone: 'attached',
    },
    exorcistSteelShield: {
      id: 'exorcistSteelShield',
      actorId: 'exorcist',
      itemDefId: 'steelShield',
      quantity: 1,
      zone: 'attached',
    },
    exorcistBandedPlateArmor: {
      id: 'exorcistBandedPlateArmor',
      actorId: 'exorcist',
      itemDefId: 'bandedPlateArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    exorcistBackpack: {
      id: 'exorcistBackpack',
      actorId: 'exorcist',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistHolyWater: {
      id: 'exorcistHolyWater',
      actorId: 'exorcist',
      itemDefId: 'holyWater',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistRope50: {
      id: 'exorcistRope50',
      actorId: 'exorcist',
      itemDefId: 'rope50',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistManacles: {
      id: 'exorcistManacles',
      actorId: 'exorcist',
      itemDefId: 'manacles',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistTorchA: { id: 'exorcistTorchA', actorId: 'exorcist', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    exorcistTorchB: { id: 'exorcistTorchB', actorId: 'exorcist', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    templarHolySymbol: {
      id: 'templarHolySymbol',
      actorId: 'templar',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
    },
    templarPolishedSword: {
      id: 'templarPolishedSword',
      actorId: 'templar',
      itemDefId: 'polishedSword',
      quantity: 1,
      zone: 'attached',
      state: { heldHands: 1 },
    },
    templarDagger: {
      id: 'templarDagger',
      actorId: 'templar',
      itemDefId: 'dagger',
      quantity: 1,
      zone: 'attached',
    },
    templarSteelShield: {
      id: 'templarSteelShield',
      actorId: 'templar',
      itemDefId: 'steelShield',
      quantity: 1,
      zone: 'attached',
    },
    templarBandedPlateArmor: {
      id: 'templarBandedPlateArmor',
      actorId: 'templar',
      itemDefId: 'bandedPlateArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    templarRidingSaddle: {
      id: 'templarRidingSaddle',
      actorId: 'templar',
      itemDefId: 'ridingSaddleTack',
      quantity: 1,
      zone: 'stowed',
    },
    templarLeatherSaddlebag: {
      id: 'templarLeatherSaddlebag',
      actorId: 'templar',
      itemDefId: 'leatherSaddlebag',
      quantity: 1,
      zone: 'stowed',
    },
    templarRation1: { id: 'templarRation1', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation2: { id: 'templarRation2', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation3: { id: 'templarRation3', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation4: { id: 'templarRation4', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation5: { id: 'templarRation5', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation6: { id: 'templarRation6', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRation7: { id: 'templarRation7', actorId: 'templar', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
  },
}
