import type { CanonicalState } from './domain/types'

export const sampleState: CanonicalState = {
  actors: {
    cutthroat: {
      id: 'cutthroat',
      name: 'Cutthroat',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      rightWieldingEntryId: 'cutthroatDagger',
    },
    prophet: {
      id: 'prophet',
      name: 'Prophet',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    exorcist: {
      id: 'exorcist',
      name: 'Exorcist',
      kind: 'pc',
      stats: { strengthMod: 1, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    templar: {
      id: 'templar',
      name: 'Templar',
      kind: 'pc',
      stats: { strengthMod: 2, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      rightWieldingEntryId: 'templarPolishedSword',
    },
    templarHorse: {
      id: 'templarHorse',
      name: 'Medium riding horse',
      kind: 'animal',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      ownerActorId: 'templar',
      capacityStone: 60,
      baseSpeedProfile: { explorationFeet: 120, combatFeet: 40, runningFeet: 120, milesPerDay: 24 },
    },
    thug: {
      id: 'thug',
      name: 'Thug',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    corsair: {
      id: 'corsair',
      name: 'Corsair',
      kind: 'pc',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      rightWieldingEntryId: 'corsairScimitar',
    },
    legionary: {
      id: 'legionary',
      name: 'Legionary',
      kind: 'pc',
      stats: { strengthMod: 1, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
    },
    cataphract: {
      id: 'cataphract',
      name: 'Cataphract',
      kind: 'pc',
      stats: { strengthMod: 2, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      rightWieldingEntryId: 'cataphractPolishedSword',
    },
    cataphractHorse: {
      id: 'cataphractHorse',
      name: 'Medium riding horse',
      kind: 'animal',
      stats: { strengthMod: 0, hasLoadBearing: false },
      movementGroupId: 'party',
      active: true,
      ownerActorId: 'cataphract',
      capacityStone: 60,
      baseSpeedProfile: { explorationFeet: 120, combatFeet: 40, runningFeet: 120, milesPerDay: 24 },
    },
  },
  movementGroups: {
    party: { id: 'party', name: 'Expedition Group', active: true },
  },
  carryGroups: {},
  itemDefinitions: {
    handAxe: { id: 'handAxe', canonicalName: 'Hand axe', kind: 'standard', sixthsPerUnit: 1 },
    dagger: { id: 'dagger', canonicalName: 'Dagger', kind: 'standard', sixthsPerUnit: 1 },
    leatherArmor: { id: 'leatherArmor', canonicalName: 'Leather armor', kind: 'armor', armorClass: 2 },
    backpack: { id: 'backpack', canonicalName: 'Backpack', kind: 'standard', sixthsPerUnit: 1 },
    ironSpike: { id: 'ironSpike', canonicalName: 'Iron spike', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    smallHammer: { id: 'smallHammer', canonicalName: 'Small hammer', kind: 'standard', sixthsPerUnit: 1 },
    militaryOil: { id: 'militaryOil', canonicalName: 'Flask of military oil', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    tinderbox: { id: 'tinderbox', canonicalName: 'Tinderbox', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    torch: { id: 'torch', canonicalName: 'Torch', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    waterskin: { id: 'waterskin', canonicalName: 'Waterskin', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    ironRationsDay: {
      id: 'ironRationsDay',
      canonicalName: 'Daily iron rations',
      kind: 'standard',
      sixthsPerUnit: 1,
      priceInGp: 1 / 7,
      isFungibleVisual: true,
    },
    holySymbolWingedSun: {
      id: 'holySymbolWingedSun',
      canonicalName: 'Holy symbol (winged sun of Ammonar)',
      kind: 'standard',
      sixthsPerUnit: 1,
    },
    sling: { id: 'sling', canonicalName: 'Sling', kind: 'standard', sixthsPerUnit: 1 },
    slingStones30: { id: 'slingStones30', canonicalName: '30 sling stones', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    staff: { id: 'staff', canonicalName: 'Staff', kind: 'bulky' },
    rope50: { id: 'rope50', canonicalName: "50' rope", kind: 'standard', sixthsPerUnit: 6 },
    warhammer: { id: 'warhammer', canonicalName: 'Warhammer', kind: 'standard', sixthsPerUnit: 1 },
    steelShield: { id: 'steelShield', canonicalName: 'Steel shield', kind: 'bulky' },
    bandedPlateArmor: { id: 'bandedPlateArmor', canonicalName: 'Banded plate armor', kind: 'armor', armorClass: 5 },
    holyWater: { id: 'holyWater', canonicalName: 'Flask of holy water', kind: 'standard', sixthsPerUnit: 1, isFungibleVisual: true },
    manacles: { id: 'manacles', canonicalName: 'Manacles', kind: 'standard', sixthsPerUnit: 1 },
    polishedSword: { id: 'polishedSword', canonicalName: 'Polished sword', kind: 'standard', sixthsPerUnit: 1 },
    ridingSaddleTack: { id: 'ridingSaddleTack', canonicalName: 'Riding saddle and tack', kind: 'standard', sixthsPerUnit: 4 },
    leatherSaddlebag: { id: 'leatherSaddlebag', canonicalName: 'Leather saddlebag', kind: 'standard', sixthsPerUnit: 3 },
    shortBow: { id: 'shortBow', canonicalName: 'Short bow', kind: 'standard', sixthsPerUnit: 1 },
    quiver20Arrows: { id: 'quiver20Arrows', canonicalName: 'Quiver with 20 arrows', kind: 'standard', sixthsPerUnit: 1 },
    morningStar: { id: 'morningStar', canonicalName: 'Morning star', kind: 'bulky' },
    chainMailArmor: { id: 'chainMailArmor', canonicalName: 'Chain mail armor', kind: 'armor', armorClass: 4 },
    greatAxe: { id: 'greatAxe', canonicalName: 'Long bearded axe (great axe)', kind: 'bulky' },
    scimitar: { id: 'scimitar', canonicalName: 'Scimitar (short sword)', kind: 'standard', sixthsPerUnit: 1 },
    shortSword: { id: 'shortSword', canonicalName: 'Short sword', kind: 'standard', sixthsPerUnit: 1 },
    woodenShield: { id: 'woodenShield', canonicalName: 'Wooden shield', kind: 'bulky' },
    javelin: { id: 'javelin', canonicalName: 'Javelin', kind: 'standard', sixthsPerUnit: 1 },
    spear: { id: 'spear', canonicalName: 'Spear', kind: 'bulky' },
    compositeBow: { id: 'compositeBow', canonicalName: 'Composite bow', kind: 'standard', sixthsPerUnit: 6 },
    lamellarArmor: { id: 'lamellarArmor', canonicalName: 'Lamellar armor', kind: 'armor', armorClass: 5 },
    messKit: { id: 'messKit', canonicalName: 'Mess kit', kind: 'standard', sixthsPerUnit: 1 },
    laborersTools: { id: 'laborersTools', canonicalName: "Laborer's tools", kind: 'standard', sixthsPerUnit: 6 },
    beltPouch: { id: 'beltPouch', canonicalName: 'Belt pouch', kind: 'standard', sixthsPerUnit: 1 },
    smallSack: { id: 'smallSack', canonicalName: 'Small sack', kind: 'standard', sixthsPerUnit: 1 },
    grapplingHook: { id: 'grapplingHook', canonicalName: 'Grappling hook', kind: 'standard', sixthsPerUnit: 1 },
    sealedStrongbox: { id: 'sealedStrongbox', canonicalName: 'Sealed strongbox', kind: 'standard', sixthsPerUnit: 6 },
    cofferOfCoins: { id: 'cofferOfCoins', canonicalName: 'Coffer of mixed coins', kind: 'standard', sixthsPerUnit: 6 },
    jeweledIdol: { id: 'jeweledIdol', canonicalName: 'Jeweled idol', kind: 'bulky' },
    silverServiceSet: { id: 'silverServiceSet', canonicalName: 'Silver service set', kind: 'standard', sixthsPerUnit: 4 },
    rubyCasket: { id: 'rubyCasket', canonicalName: 'Ruby-inlaid casket', kind: 'standard', sixthsPerUnit: 3 },
    goldIngot: { id: 'goldIngot', canonicalName: 'Gold ingot', kind: 'standard', sixthsPerUnit: 1 },
  },
  inventoryEntries: {
    cutthroatHandAxe: {
      id: 'cutthroatHandAxe',
      actorId: 'cutthroat',
      itemDefId: 'handAxe',
      quantity: 1,
      zone: 'attached',
    },
    cutthroatDagger: {
      id: 'cutthroatDagger',
      actorId: 'cutthroat',
      itemDefId: 'dagger',
      quantity: 1,
      zone: 'attached',
    },
    cutthroatLeatherArmor: {
      id: 'cutthroatLeatherArmor',
      actorId: 'cutthroat',
      itemDefId: 'leatherArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    cutthroatBackpack: {
      id: 'cutthroatBackpack',
      actorId: 'cutthroat',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatIronSpike: {
      id: 'cutthroatIronSpike',
      actorId: 'cutthroat',
      itemDefId: 'ironSpike',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatSmallHammer: {
      id: 'cutthroatSmallHammer',
      actorId: 'cutthroat',
      itemDefId: 'smallHammer',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatMilitaryOil: {
      id: 'cutthroatMilitaryOil',
      actorId: 'cutthroat',
      itemDefId: 'militaryOil',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatTinderbox: {
      id: 'cutthroatTinderbox',
      actorId: 'cutthroat',
      itemDefId: 'tinderbox',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatTorches: { id: 'cutthroatTorches', actorId: 'cutthroat', itemDefId: 'torch', quantity: 3, zone: 'accessible' },
    cutthroatWaterskin: {
      id: 'cutthroatWaterskin',
      actorId: 'cutthroat',
      itemDefId: 'waterskin',
      quantity: 1,
      zone: 'stowed',
    },
    cutthroatRations1: { id: 'cutthroatRations1', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations2: { id: 'cutthroatRations2', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations3: { id: 'cutthroatRations3', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations4: { id: 'cutthroatRations4', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations5: { id: 'cutthroatRations5', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations6: { id: 'cutthroatRations6', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cutthroatRations7: { id: 'cutthroatRations7', actorId: 'cutthroat', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetHolySymbol: {
      id: 'prophetHolySymbol',
      actorId: 'prophet',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    prophetSling: {
      id: 'prophetSling',
      actorId: 'prophet',
      itemDefId: 'sling',
      quantity: 1,
      zone: 'attached',
    },
    prophetSlingStones: {
      id: 'prophetSlingStones',
      actorId: 'prophet',
      itemDefId: 'slingStones30',
      quantity: 1,
      zone: 'accessible',
    },
    prophetStaff: {
      id: 'prophetStaff',
      actorId: 'prophet',
      itemDefId: 'staff',
      quantity: 1,
      zone: 'attached',
    },
    prophetLeatherArmor: {
      id: 'prophetLeatherArmor',
      actorId: 'prophet',
      itemDefId: 'leatherArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    prophetBackpack: {
      id: 'prophetBackpack',
      actorId: 'prophet',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    prophetRations1: { id: 'prophetRations1', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations2: { id: 'prophetRations2', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations3: { id: 'prophetRations3', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations4: { id: 'prophetRations4', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations5: { id: 'prophetRations5', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations6: { id: 'prophetRations6', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    prophetRations7: { id: 'prophetRations7', actorId: 'prophet', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    exorcistHolySymbol: {
      id: 'exorcistHolySymbol',
      actorId: 'exorcist',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
    },
    exorcistWarhammer: {
      id: 'exorcistWarhammer',
      actorId: 'exorcist',
      itemDefId: 'warhammer',
      quantity: 1,
      zone: 'attached',
    },
    exorcistSteelShield: {
      id: 'exorcistSteelShield',
      actorId: 'exorcist',
      itemDefId: 'steelShield',
      quantity: 1,
      zone: 'attached',
    },
    exorcistBandedPlateArmor: {
      id: 'exorcistBandedPlateArmor',
      actorId: 'exorcist',
      itemDefId: 'bandedPlateArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    exorcistBackpack: {
      id: 'exorcistBackpack',
      actorId: 'exorcist',
      itemDefId: 'backpack',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistHolyWater: {
      id: 'exorcistHolyWater',
      actorId: 'exorcist',
      itemDefId: 'holyWater',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistRope50: {
      id: 'exorcistRope50',
      actorId: 'exorcist',
      itemDefId: 'rope50',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistManacles: {
      id: 'exorcistManacles',
      actorId: 'exorcist',
      itemDefId: 'manacles',
      quantity: 1,
      zone: 'stowed',
    },
    exorcistTorchA: { id: 'exorcistTorchA', actorId: 'exorcist', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    exorcistTorchB: { id: 'exorcistTorchB', actorId: 'exorcist', itemDefId: 'torch', quantity: 1, zone: 'accessible' },
    templarHolySymbol: {
      id: 'templarHolySymbol',
      actorId: 'templar',
      itemDefId: 'holySymbolWingedSun',
      quantity: 1,
      zone: 'worn',
    },
    templarPolishedSword: {
      id: 'templarPolishedSword',
      actorId: 'templar',
      itemDefId: 'polishedSword',
      quantity: 1,
      zone: 'attached',
    },
    templarDagger: {
      id: 'templarDagger',
      actorId: 'templar',
      itemDefId: 'dagger',
      quantity: 1,
      zone: 'attached',
    },
    templarSteelShield: {
      id: 'templarSteelShield',
      actorId: 'templar',
      itemDefId: 'steelShield',
      quantity: 1,
      zone: 'attached',
    },
    templarBandedPlateArmor: {
      id: 'templarBandedPlateArmor',
      actorId: 'templar',
      itemDefId: 'bandedPlateArmor',
      quantity: 1,
      zone: 'worn',
      state: { worn: true },
    },
    templarRidingSaddle: {
      id: 'templarRidingSaddle',
      actorId: 'templarHorse',
      itemDefId: 'ridingSaddleTack',
      quantity: 1,
      zone: 'stowed',
    },
    templarLeatherSaddlebag: {
      id: 'templarLeatherSaddlebag',
      actorId: 'templarHorse',
      itemDefId: 'leatherSaddlebag',
      quantity: 1,
      zone: 'stowed',
    },
    templarRations1: { id: 'templarRations1', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations2: { id: 'templarRations2', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations3: { id: 'templarRations3', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations4: { id: 'templarRations4', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations5: { id: 'templarRations5', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations6: { id: 'templarRations6', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    templarRations7: { id: 'templarRations7', actorId: 'templarHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugShortBow: { id: 'thugShortBow', actorId: 'thug', itemDefId: 'shortBow', quantity: 1, zone: 'attached' },
    thugQuiver: { id: 'thugQuiver', actorId: 'thug', itemDefId: 'quiver20Arrows', quantity: 1, zone: 'attached' },
    thugMorningStar: { id: 'thugMorningStar', actorId: 'thug', itemDefId: 'morningStar', quantity: 1, zone: 'attached' },
    thugLeatherArmor: { id: 'thugLeatherArmor', actorId: 'thug', itemDefId: 'leatherArmor', quantity: 1, zone: 'worn', state: { worn: true } },
    thugBackpack: { id: 'thugBackpack', actorId: 'thug', itemDefId: 'backpack', quantity: 1, zone: 'stowed' },
    thugWaterskin: { id: 'thugWaterskin', actorId: 'thug', itemDefId: 'waterskin', quantity: 1, zone: 'stowed' },
    thugRations1: { id: 'thugRations1', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations2: { id: 'thugRations2', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations3: { id: 'thugRations3', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations4: { id: 'thugRations4', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations5: { id: 'thugRations5', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations6: { id: 'thugRations6', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    thugRations7: { id: 'thugRations7', actorId: 'thug', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairShortBow: { id: 'corsairShortBow', actorId: 'corsair', itemDefId: 'shortBow', quantity: 1, zone: 'attached' },
    corsairQuiver: { id: 'corsairQuiver', actorId: 'corsair', itemDefId: 'quiver20Arrows', quantity: 1, zone: 'attached' },
    corsairScimitar: { id: 'corsairScimitar', actorId: 'corsair', itemDefId: 'scimitar', quantity: 1, zone: 'attached' },
    corsairDaggerA: { id: 'corsairDaggerA', actorId: 'corsair', itemDefId: 'dagger', quantity: 1, zone: 'attached' },
    corsairDaggerB: { id: 'corsairDaggerB', actorId: 'corsair', itemDefId: 'dagger', quantity: 1, zone: 'attached' },
    corsairLeatherArmor: { id: 'corsairLeatherArmor', actorId: 'corsair', itemDefId: 'leatherArmor', quantity: 1, zone: 'worn', state: { worn: true } },
    corsairSmallSack: { id: 'corsairSmallSack', actorId: 'corsair', itemDefId: 'smallSack', quantity: 1, zone: 'stowed' },
    corsairRope50: { id: 'corsairRope50', actorId: 'corsair', itemDefId: 'rope50', quantity: 1, zone: 'stowed' },
    corsairGrapplingHook: { id: 'corsairGrapplingHook', actorId: 'corsair', itemDefId: 'grapplingHook', quantity: 1, zone: 'stowed' },
    corsairWaterskin: { id: 'corsairWaterskin', actorId: 'corsair', itemDefId: 'waterskin', quantity: 1, zone: 'stowed' },
    corsairRations1: { id: 'corsairRations1', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations2: { id: 'corsairRations2', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations3: { id: 'corsairRations3', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations4: { id: 'corsairRations4', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations5: { id: 'corsairRations5', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations6: { id: 'corsairRations6', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    corsairRations7: { id: 'corsairRations7', actorId: 'corsair', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionarySpear: { id: 'legionarySpear', actorId: 'legionary', itemDefId: 'spear', quantity: 1, zone: 'attached' },
    legionaryShortSword: { id: 'legionaryShortSword', actorId: 'legionary', itemDefId: 'shortSword', quantity: 1, zone: 'attached' },
    legionarySteelShield: { id: 'legionarySteelShield', actorId: 'legionary', itemDefId: 'steelShield', quantity: 1, zone: 'attached' },
    legionaryBandedPlate: { id: 'legionaryBandedPlate', actorId: 'legionary', itemDefId: 'bandedPlateArmor', quantity: 1, zone: 'worn', state: { worn: true } },
    legionaryBackpack: { id: 'legionaryBackpack', actorId: 'legionary', itemDefId: 'backpack', quantity: 1, zone: 'stowed' },
    legionaryLaborersTools: { id: 'legionaryLaborersTools', actorId: 'legionary', itemDefId: 'laborersTools', quantity: 1, zone: 'stowed' },
    legionaryMessKit: { id: 'legionaryMessKit', actorId: 'legionary', itemDefId: 'messKit', quantity: 1, zone: 'stowed' },
    legionaryMilitaryOil: { id: 'legionaryMilitaryOil', actorId: 'legionary', itemDefId: 'militaryOil', quantity: 1, zone: 'stowed' },
    legionaryTinderbox: { id: 'legionaryTinderbox', actorId: 'legionary', itemDefId: 'tinderbox', quantity: 1, zone: 'stowed' },
    legionaryWaterskin: { id: 'legionaryWaterskin', actorId: 'legionary', itemDefId: 'waterskin', quantity: 1, zone: 'stowed' },
    legionaryRations1: { id: 'legionaryRations1', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations2: { id: 'legionaryRations2', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations3: { id: 'legionaryRations3', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations4: { id: 'legionaryRations4', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations5: { id: 'legionaryRations5', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations6: { id: 'legionaryRations6', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    legionaryRations7: { id: 'legionaryRations7', actorId: 'legionary', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractCompositeBow: { id: 'cataphractCompositeBow', actorId: 'cataphract', itemDefId: 'compositeBow', quantity: 1, zone: 'attached' },
    cataphractQuiver: { id: 'cataphractQuiver', actorId: 'cataphract', itemDefId: 'quiver20Arrows', quantity: 1, zone: 'attached' },
    cataphractPolishedSword: { id: 'cataphractPolishedSword', actorId: 'cataphract', itemDefId: 'polishedSword', quantity: 1, zone: 'attached' },
    cataphractSteelShield: { id: 'cataphractSteelShield', actorId: 'cataphract', itemDefId: 'steelShield', quantity: 1, zone: 'attached' },
    cataphractLamellarArmor: { id: 'cataphractLamellarArmor', actorId: 'cataphract', itemDefId: 'lamellarArmor', quantity: 1, zone: 'worn', state: { worn: true } },
    cataphractWaterskin: { id: 'cataphractWaterskin', actorId: 'cataphract', itemDefId: 'waterskin', quantity: 1, zone: 'stowed' },
    cataphractRidingSaddle: { id: 'cataphractRidingSaddle', actorId: 'cataphractHorse', itemDefId: 'ridingSaddleTack', quantity: 1, zone: 'stowed' },
    cataphractSaddlebag: { id: 'cataphractSaddlebag', actorId: 'cataphractHorse', itemDefId: 'leatherSaddlebag', quantity: 1, zone: 'stowed' },
    cataphractRations1: { id: 'cataphractRations1', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations2: { id: 'cataphractRations2', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations3: { id: 'cataphractRations3', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations4: { id: 'cataphractRations4', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations5: { id: 'cataphractRations5', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations6: { id: 'cataphractRations6', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
    cataphractRations7: { id: 'cataphractRations7', actorId: 'cataphractHorse', itemDefId: 'ironRationsDay', quantity: 1, zone: 'stowed' },
  },
}
